language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-opengl-dev zlib1g-dev
script: qmake CFLAGS="-Werror" CXXFLAGS="-Werror" && make
