language: cpp
compiler:
  - gcc
  - clang
before_install:
  - yes | sudo add-apt-repository ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev qtdeclarative5-dev qtbase5-dev
script: qmake -qt=qt5 -r && make
